import { spawn } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Command } from 'commander';
import { runOneShotWithNotify } from '../shared/notify';

interface LoadEnvOptions {
  envFile?: string;
  mode: 'both' | 'launchctl' | 'shell';
  shellRcOutput: string;
  dryRun: boolean;
}

interface ParsedEntry {
  key: string;
  value: string;
}

const KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

function parseEnvFile(content: string): ParsedEntry[] {
  const out: ParsedEntry[] = [];
  for (const rawLine of content.split('\n')) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('export ')) line = line.slice('export '.length).trim();

    const eqIdx = line.indexOf('=');
    if (eqIdx < 0) continue;
    const key = line.slice(0, eqIdx).trim();
    let value = line.slice(eqIdx + 1).trim();

    if (!KEY_RE.test(key)) {
      console.warn(`[boot-tasks load-env] skip invalid key: ${key}`);
      continue;
    }

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    out.push({ key, value });
  }
  return out;
}

function runLaunchctl(key: string, value: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn('/bin/launchctl', ['setenv', key, value], { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    proc.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`launchctl setenv ${key} failed (code ${code}): ${stderr.trim()}`));
    });
    proc.on('error', (err) => reject(err));
  });
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function writeShellRc(entries: ParsedEntry[], outputPath: string): void {
  const header = [
    '# Auto-generated by boot-tasks load-env. Do not edit by hand.',
    `# Generated at: ${new Date().toISOString()}`,
    '# To consume: add the following line to ~/.zshenv (or ~/.bashrc):',
    `#   [ -f ${outputPath} ] && source ${outputPath}`,
    '',
  ].join('\n');
  const body = entries.map((e) => `export ${e.key}=${shellQuote(e.value)}`).join('\n') + '\n';
  fs.writeFileSync(outputPath, header + body, { mode: 0o600 });
}

async function runLoadEnv(opts: LoadEnvOptions): Promise<{ summary: string }> {
  if (!opts.envFile) {
    throw new Error('必须提供 --env-file <path>(指向 .env 文件)');
  }

  const envPath = path.resolve(opts.envFile.replace(/^~/, os.homedir()));
  if (!fs.existsSync(envPath)) {
    throw new Error(`.env 文件不存在: ${envPath}`);
  }

  const content = fs.readFileSync(envPath, 'utf8');
  const entries = parseEnvFile(content);

  if (entries.length === 0) {
    throw new Error(`.env 文件解析后为空(没找到 KEY=VALUE): ${envPath}`);
  }

  const summaryLines: string[] = [
    `**来源**: \`${envPath}\``,
    `**解析到**: ${entries.length} 个 env 变量`,
    `**模式**: \`${opts.mode}\``,
  ];

  if (opts.dryRun) {
    summaryLines.push('', '**dry-run**: 已解析但未写入');
    summaryLines.push('', '**键列表**:', entries.map((e) => `- \`${e.key}\``).join('\n'));
    console.log(summaryLines.join('\n'));
    return { summary: summaryLines.join('\n') };
  }

  let launchctlCount = 0;
  let shellCount = 0;

  if (opts.mode === 'launchctl' || opts.mode === 'both') {
    for (const { key, value } of entries) {
      await runLaunchctl(key, value);
      launchctlCount++;
    }
    summaryLines.push(`**launchctl setenv**: 写入 ${launchctlCount} 个`);
  }

  if (opts.mode === 'shell' || opts.mode === 'both') {
    const rcPath = path.resolve(opts.shellRcOutput.replace(/^~/, os.homedir()));
    writeShellRc(entries, rcPath);
    shellCount = entries.length;
    summaryLines.push(
      `**shell rc**: 写入 ${shellCount} 个 → \`${rcPath}\``,
      '',
      `**首次使用**: 在 \`~/.zshenv\` 加一行 \`[ -f ${rcPath} ] && source ${rcPath}\``,
    );
  }

  summaryLines.push('', '**键列表**:', entries.map((e) => `- \`${e.key}\``).join('\n'));

  console.log(summaryLines.join('\n'));
  return { summary: summaryLines.join('\n') };
}

export function registerLoadEnv(program: Command): void {
  program
    .command('load-env')
    .description('读取 .env 文件,把变量注入到 launchctl 和/或 shell rc(GUI + terminal 都生效)')
    .option('-f, --env-file <path>', '.env 文件路径(支持 ~)')
    .option('-m, --mode <mode>', '注入模式: launchctl | shell | both', 'both')
    .option('--shell-rc-output <path>', 'shell mode 写入路径', '~/.boot-tasks-env')
    .option('--dry-run', '只解析不写入', false)
    .action((opts: LoadEnvOptions) => {
      runOneShotWithNotify({
        command: 'load-env',
        run: () => runLoadEnv(opts),
      });
    });
}
