import { spawn } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Command } from 'commander';
import { runOneShotWithNotify } from '../shared/notify';
import type { SubTask, SubTaskContext, SubTaskHandle, SubTaskResult } from '../shared/sub-task';

export interface LoadEnvOptions {
  envPath?: string;
  mode: 'both' | 'launchctl' | 'zshrc';
  zshrcPath: string;
  dryRun: boolean;
}

const MARKER_BEGIN = '# >>> boot-tasks load-env >>>';
const MARKER_END = '# <<< boot-tasks load-env <<<';

interface ParsedEntry {
  key: string;
  value: string;
}

const KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

function parseEnvFile(content: string): ParsedEntry[] {
  const out: ParsedEntry[] = [];
  for (const rawLine of content.split('\n')) {
    let line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('export ')) line = line.slice('export '.length).trim();

    const eqIdx = line.indexOf('=');
    if (eqIdx < 0) continue;
    const key = line.slice(0, eqIdx).trim();
    let value = line.slice(eqIdx + 1).trim();

    if (!KEY_RE.test(key)) {
      console.warn(`[boot-tasks load-env] skip invalid key: ${key}`);
      continue;
    }

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    out.push({ key, value });
  }
  return out;
}

function runLaunchctl(key: string, value: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn('/bin/launchctl', ['setenv', key, value], { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    proc.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`launchctl setenv ${key} failed (code ${code}): ${stderr.trim()}`));
    });
    proc.on('error', (err) => reject(err));
  });
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function buildZshrcBlock(entries: ParsedEntry[]): string {
  const lines = [
    MARKER_BEGIN,
    `# Auto-generated by boot-tasks load-env at ${new Date().toISOString()}.`,
    '# Do not edit by hand — this block is replaced wholesale on each run.',
    ...entries.map((e) => `export ${e.key}=${shellQuote(e.value)}`),
    MARKER_END,
  ];
  return lines.join('\n');
}

function updateZshrc(entries: ParsedEntry[], zshrcPath: string): 'replaced' | 'appended' | 'created' {
  const block = buildZshrcBlock(entries);
  let existing = '';
  let mode: 'replaced' | 'appended' | 'created' = 'created';

  if (fs.existsSync(zshrcPath)) {
    existing = fs.readFileSync(zshrcPath, 'utf8');
    const beginIdx = existing.indexOf(MARKER_BEGIN);
    const endIdx = existing.indexOf(MARKER_END);
    if (beginIdx >= 0 && endIdx > beginIdx) {
      const before = existing.slice(0, beginIdx).replace(/\n+$/, '\n');
      const after = existing.slice(endIdx + MARKER_END.length).replace(/^\n+/, '\n');
      fs.writeFileSync(zshrcPath, before + block + after);
      return 'replaced';
    }
    mode = 'appended';
  }

  const prefix = existing.length === 0 ? '' : (existing.endsWith('\n') ? '\n' : '\n\n');
  fs.writeFileSync(zshrcPath, existing + prefix + block + '\n');
  return mode;
}

async function runLoadEnv(opts: LoadEnvOptions): Promise<{ summary: string }> {
  if (!opts.envPath) {
    throw new Error('必须提供 --env-path <path>(指向 .env 文件)');
  }

  const envPath = path.resolve(opts.envPath.replace(/^~/, os.homedir()));
  if (!fs.existsSync(envPath)) {
    throw new Error(`.env 文件不存在: ${envPath}`);
  }

  const content = fs.readFileSync(envPath, 'utf8');
  const entries = parseEnvFile(content);

  if (entries.length === 0) {
    throw new Error(`.env 文件解析后为空(没找到 KEY=VALUE): ${envPath}`);
  }

  const summaryLines: string[] = [
    `**来源**: \`${envPath}\``,
    `**解析到**: ${entries.length} 个 env 变量`,
    `**模式**: \`${opts.mode}\``,
  ];

  if (opts.dryRun) {
    summaryLines.push('', '**dry-run**: 已解析但未写入');
    summaryLines.push('', '**键列表**:', entries.map((e) => `- \`${e.key}\``).join('\n'));
    console.log(summaryLines.join('\n'));
    return { summary: summaryLines.join('\n') };
  }

  let launchctlCount = 0;

  if (opts.mode === 'launchctl' || opts.mode === 'both') {
    for (const { key, value } of entries) {
      await runLaunchctl(key, value);
      launchctlCount++;
    }
    summaryLines.push(`**launchctl setenv**: 写入 ${launchctlCount} 个`);
  }

  if (opts.mode === 'zshrc' || opts.mode === 'both') {
    const rcPath = path.resolve(opts.zshrcPath.replace(/^~/, os.homedir()));
    const action = updateZshrc(entries, rcPath);
    const actionLabel = action === 'replaced' ? '替换现有 block' : action === 'appended' ? '追加新 block' : '新建文件';
    summaryLines.push(`**~/.zshrc**: ${actionLabel} → \`${rcPath}\` (${entries.length} 个 export)`);
  }

  summaryLines.push('', '**键列表**:', entries.map((e) => `- \`${e.key}\``).join('\n'));

  console.log(summaryLines.join('\n'));
  return { summary: summaryLines.join('\n') };
}

// 包装 runLoadEnv 成 SubTask。supervisor 模式下不发飞书、不 process.exit。
// runLoadEnv 内部已经返回 summary,这里只搬运结果与异常。
export function createLoadEnvTask(opts: LoadEnvOptions): SubTask {
  return {
    name: 'load-env',
    kind: 'one-shot',
    async start(ctx: SubTaskContext): Promise<SubTaskHandle> {
      const promise = (async (): Promise<SubTaskResult> => {
        if (ctx.stopped) {
          return { status: 'success', summary: '启动前 supervisor 已停止,跳过' };
        }
        try {
          const result = await runLoadEnv(opts);
          return { status: 'success', summary: result.summary };
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          return { status: 'failed', error: message };
        }
      })();
      return { promise };
    },
  };
}

export function registerLoadEnv(program: Command): void {
  program
    .command('load-env')
    .description('读取 .env 文件,把变量注入到 launchctl 和/或 ~/.zshrc(GUI + terminal 都生效)')
    .option('-f, --env-path <path>', '.env 文件路径(支持 ~)')
    .option('-m, --mode <mode>', '注入模式: launchctl | zshrc | both', 'both')
    .option('--zshrc-path <path>', 'zshrc mode 写入路径(用 marker block 替换)', '~/.zshrc')
    .option('--dry-run', '只解析不写入', false)
    .action((opts: LoadEnvOptions) => {
      runOneShotWithNotify({
        command: 'load-env',
        run: () => runLoadEnv(opts),
      });
    });
}
